<!-- _layouts/default.html -->

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page.title }}</title>
  <link rel="stylesheet" href="{{ "/assets/css/styles.css" | relative_url }}">
</head>
<body>
  <header>
    <nav>
      <h1>{{ site.navbar.title }}</h1>
      <ul>
        {% for item in site.navbar.items %}
          <li>
            <a href="{{ /SPatten_Semester_Project.html }}">{{ place 1 }}</a>
            {% if item.subitems %}
              <ul>
                {% for subitem in item.subitems %}
                  <li><a href="{{ /SPatten_Semester_Project.html }}">{{ place 2 }}</a></li>
                {% endfor %}
              </ul>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </nav>
  </header>
  <!-- Other content sections -->
  {{ content }}
</body>
</html>
