title: Spencer Patten
email: spencer.patten@hotmail.com
description: >- 
This site serves as a hub for the work of Spencer Patten

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spatten3.github.io/" # the base hostname & protocol for your site
github_username:  SPatten3

# Build settings
markdown: kramdown
theme: minimal
