---
title: ""
---

<br />

# Resume {.tabset .tabset-pills}

<br />

## Education

<br />

<div style="float:left">

### Brigham Young University - Idaho


<div style="float:right;color:gray;text-align:right">

2023 - 2027

GPA: 3.8

</div>


<div style="color:gray;width:75%">

**Bachelor of Science: Psychology**

* Major Emphasis: Industrial Organizational Psychology

* Minor: Statistics

* Certificate: Human Resources Management

**Vice President: BYU-Idaho Firm Foundations Society**

* Guiding and instructing members in use of the Socratic method of inquiry, historical-critical method, and other processes applied to religious and philosophical questions

* Participating in a leadership council to make goals and plans regarding societal growth

* Presiding at and conducting meetings, including presenting, leading discussions, and introducing guest speakers

**Member: Students Promoting Industrial Organizational Psychology**

</div>
</div>

<div style="clear:both;"></div>

<br />

<div style="float:right;color:gray;text-align:right">

<br />

Class of 2021

</div>


<div style="color:gray;width:75%">


<div style="float:left">

### Rogers Senior High School

<div style="color:gray">

**High School Diploma**

</div>

</div>

<div style="clear:both;"></div>

## Work Experience

<div style="float:left">

<br />

### BYU-Idaho Study Skills Center

<div style="float:right;color:gray;text-align:right">

January 2024 - Present

Rexburg, ID

</div>

<div style="color:gray;width:75%">

**Academic Skills Coach**

* Guiding undergraduate students-clients through goal setting and execution processes for semester length periods in a one on one setting

* Studying and applying principles for organizational and personal development materials from sources such as Franklin-Covey, the Arbinger Insititute etc.

* Applying learning theory in individualized settings for personal and academic development

**Team Leader**

* Instructing supervised employees biweekly in group and individualized settings regarding methods of job performance and enhancement

* Overseeing and approving time sheets for supervised employees on a weekly basis

* Generating organization-wide employee evaluations based on student-client feedback through RStudio, a statistical analysis and visualization software

</div>

</div>


<div style="clear:both;"></div>

<div style="float:left">

<br />

### Northway Academy



<div style="float:right;color:gray;text-align:right">

May - September 2024

Elk River, MN

</div>

<div style="color:gray;width:75%">

**Behavior Technician**

* Provided applied behavioral analysis therapy to individuals with autism spectrum disorder 8 to 17 years of age in a clinical setting under direction of a board certified behavior analyst

* Instructed high functioning school aged clients in relevant reading, writing, and mathematics to supplement academic abilities to one day attend school full time

* Implemented individualized guidance with clients in daily living skills to establish independence

</div>

</div>

<div style="clear:both;"></div>

<div style="float:left">

<br />

### C&J Relocation Services

<div style="float:right;color:gray;text-align:right">

June - October 2021

Cambridge, MN

</div>

<div style="color:gray;width:75%">

**Crew Member**

* Coordinated efforts to prepare a trailer to safely transport client belongings up to 100 miles

* Packed loose goods into small, medium, and large boxes using packing paper, shrink wrap, and other methods to ensure 100% safety during transportation

* Transported client belongings to and from trailer using straps, harnesses, and hand trucks to ensure 100% safety during handling

</div>

</div>

<div style="clear:both;"></div>

## Skills

<br />

**RStudio**

* Data Visualization with GGPlot2 and Plotly

* Data wrangling with DPLYR and Base R functions

* Generating Statistical Analyses

* Managing a github pages webiste from within RStudio

## Volunteer Experience

<br />

### Full Time Missionary: The Church of Jesus Christ of Latter-day Saints

<div style="float:right;color:gray;text-align:right">

October 2021 - October 2023

Northern Utah

</div>

<div style="color:gray;width:75%">

* Acted as an ordained minister, specializing in teaching from scriptures and supporting individual growth through 20 to 25 teaching appointments per week

* Offering humanitarian aid through service at non-profit welfare organizations and personalized service projects at least once a week

* Supervised volunteer efforts by analyzing key indicators of performance and engaging 

* Counseling with volunteer and local ecclesiastical leaders on a weekly basis in order to improve effectiveness and performance

</div>

</div>

<div style="clear:both;"></div>


<!-- TEMPLATE FOR NEW SECTIONS


<div style="float:left">

### Name of the Section 

<br />

<div style="color:gray">

--- Main Body Text (left aligned) ---






--- End Main Body Text ---

</div>

</div>

<div style="float:right;color:gray;text-align:right">

<br />

--- Informative Text (right aligned)---



--- End Informative Text ---

</div>

<div style="clear:both;"></div>

-->